---
apiVersion: v1
kind: Service
metadata:
  name: scaphandre-pve0
  namespace: monitoring
  labels:
    app: scaphandre-pve0
spec:
  ports:
  - name: metrics
    port: 9898
    protocol: TCP
    targetPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: scaphandre-pve1
  namespace: monitoring
  labels:
    app: scaphandre-pve1
spec:
  ports:
  - name: metrics
    port: 9898
    protocol: TCP
    targetPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: scaphandre-pve2
  namespace: monitoring
  labels:
    app: scaphandre-pve2
spec:
  ports:
  - name: metrics
    port: 9898
    protocol: TCP
    targetPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: scaphandre-pve3
  namespace: monitoring
  labels:
    app: scaphandre-pve3
spec:
  ports:
  - name: metrics
    port: 9898
    protocol: TCP
    targetPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: scaphandre-pve4
  namespace: monitoring
  labels:
    app: scaphandre-pve4
spec:
  ports:
  - name: metrics
    port: 9898
    protocol: TCP
    targetPort: 9898
---
apiVersion: v1
kind: Endpoints
metadata:
  name: scaphandre-pve0
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.10.10
    ports:
      - name: metrics
        port: 9898
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: scaphandre-pve1
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.10.11
    ports:
      - name: metrics
        port: 9898
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: scaphandre-pve2
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.10.12
    ports:
      - name: metrics
        port: 9898
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: scaphandre-pve3
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.10.13
    ports:
      - name: metrics
        port: 9898
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: scaphandre-pve4
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.10.14
    ports:
      - name: metrics
        port: 9898
        protocol: TCP
