---
apiVersion: v1
kind: Namespace
metadata:
  name: tempo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: flux-system
spec:
  interval: 24h
  url: https://grafana-community.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: 1.26.4
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
      interval: 12h

  values:
    reportingEnabled: false
    persistence:
      enabled: true
      size: 1Gi
      # storageClassName: zfs
    tempo:
      image:
        registry: harbor.oodrive.net/docker
        repository: grafana/tempo
        tag: 2.10.1
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
      retention: 1h
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      metricsGenerator:
        enabled: true
        remoteWriteUrl: http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/write
        storage:
          path: /tmp/tempo
        registry:
          external_labels:
            source: tempo
        processor:
          local_blocks:
            flush_to_storage: true
            filter_server_spans: false
            max_block_duration: 1m
          service_graphs:
            wait: 10s
            max_items: 10000
          span_metrics:
            enable_target_info: true

