---
apiVersion: v1
kind: Namespace
metadata:
  name: flowise
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flowise
  namespace: flux-system
spec:
  interval: 24h
  url: https://cowboysysop.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flowise
  namespace: flowise
spec:
  interval: 30m
  chart:
    spec:
      chart: flowise
      version: 3.11.2
      sourceRef:
        kind: HelmRepository
        name: flowise
        namespace: flux-system
      interval: 12h

  values:
    extraEnvVars:
      - name: FLOWISE_FILE_SIZE_LIMIT
        value: "200mb"
    persistence:
      enabled: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/buffering: |
          maxrequestbodybytes: 200000000
        cert-manager.io/cluster-issuer: le-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Flowise"
        gethomepage.dev/group: "Apps"
      hosts:
         - host: ${flowiseIngressHost}
           paths:
             - /
      tls:
        - secretName: flowise-tls
          hosts:
            - ${flowiseIngressHost}

