---
apiVersion: v1
kind: Namespace
metadata:
  name: kubedoom
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubedoom
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.christianhuth.de
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubedoom
  namespace: kubedoom
spec:
  interval: 30m
  chart:
    spec:
      chart: kubedoom
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: kubedoom
        namespace: flux-system
      interval: 12h

  values:
    kubedoom:
      mode: "pods"
      namespace: "kubedoom"