apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubedoom.namespace.yaml
- kubedoom.helmrepository.yaml
- kubedoom.helmrelease.yaml
- novnc.namespace.yaml
- novnc.helmrepository.yaml
- novnc.helmrelease.yaml
