---
apiVersion: v1
kind: Namespace
metadata:
  name: novnc
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: novnc
  namespace: flux-system
spec:
  interval: 24h
  url: https://nicholaswilde.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: novnc
  namespace: novnc
spec:
  interval: 30m
  chart:
    spec:
      chart: novnc
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: novnc
        namespace: flux-system
      interval: 12h

  values:
    env:
      REMOTE_HOST: "kubedoom.kubedoom"
      REMOTE_PORT: "5900"
