apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-vars
  namespace: flux-system
data:
  homepageHostname: "homepage.homelab.vincentdupain.com"
  ollamaHostname: "ollama.homelab.vincentdupain.com"
  openwebuiHostname: "open-webui.homelab.vincentdupain.com"
  podinfoHostname: "podinfo.homelab.vincentdupain.com"