apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-vars
  namespace: flux-system
data:
  homepageIngressHost: "homepage.homelab.vincentdupain.com"
  ollamaIngressHost: "ollama.homelab.vincentdupain.com"
  openwebuiIngressHost: "open-webui.homelab.vincentdupain.com"
  podinfoIngressHost: "podinfo.homelab.vincentdupain.com"