---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-example
  namespace: cloudnative-pg
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0
  
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi
 
  monitoring:
    enablePodMonitor: true
