---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
  labels:
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 24h
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 30m
  chart:
    spec:
      chart: falco
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system
      interval: 12h
  releaseName: falco
  
  valuesFrom:
  - kind: ConfigMap
    name: falco-values
    valuesKey: values.yaml
