---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 24h
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: fluent-bit
      version: 0.47.9
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      interval: 12h
  releaseName: fluent
  
  valuesFrom:
  - kind: ConfigMap
    name: fluent-values
    valuesKey: values.yaml