apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: obi
  namespace: otel
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-ebpf-instrumentation
      version: 0.4.3
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      interval: 12h

  values:
    env:
      OTEL_EBPF_KUBE_CLUSTER_NAME: "staging"
    config:
      data:
        metrics:
          features:
            - 'application' # Application-level metrics
            # - 'application_span' # Application-level trace span metrics in legacy format (like traces_spanmetrics_latency)
            - 'application_span_otel' # Application-level trace span metrics in OpenTelemetry format (like traces_span_metrics_calls_total)
            - 'application_service_graph' #  Application-level service graph metrics
        discovery:
          instrument:
            - k8s_namespace: petclinic
            - k8s_namespace: podinfo
            - k8s_namespace: default
            - k8s_namespace: client-api
            - k8s_namespace: cart-api
            - k8s_namespace: mongodb
            - k8s_namespace: monitoring
            - k8s_namespace: cloudnative-pg
            - k8s_namespace: homepage
            - k8s_namespace: cert-manager
            - k8s_namespace: coredns
            - k8s_namespace: kube-system            
        routes:
          ignore_mode: traces
          ignored_patterns:
            - /sample/manage/health/readiness
            - /sample/manage/prometheus

        log_level: info
        otel_traces_export:
          endpoint: "http://otel-gateway-opentelemetry-collector.otel:4318"
        otel_metrics_export:
          endpoint: "http://otel-gateway-opentelemetry-collector.otel:4318"
        attributes:
          kubernetes:
            enable: true
