apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-gateway
  namespace: otel
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.145.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      interval: 12h

  values:
    mode: deployment
    image:
      repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
    ports:
      jaeger-compact:
        enabled: false
      jaeger-thrift:
        enabled: false
      jaeger-grpc:
        enabled: false
      zipkin:
        enabled: false
    config:
      receivers:
        jaeger: null
        zipkin: null
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      processors:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
        batch:
          send_batch_size: 10000
          timeout: 10s
        # https://opentelemetry.io/blog/2022/tail-sampling/
        tail_sampling:
          decision_wait: 10s
          num_traces: 10000
          expected_new_traces_per_sec: 100
          policies:
            # - name: latency_policy
            #   type: latency
            #   latency:
            #     threshold_ms: 200
            - name: error_policy
              type: status_code
              status_code:
                status_codes:
                  - ERROR
            - name: randomized-policy
              type: probabilistic
              probabilistic: { sampling_percentage: 10.0 }
      exporters:
        debug: {}
        otlp_http/collector:
          endpoint: http://otel-collector-opentelemetry-collector.otel:4318

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [memory_limiter, tail_sampling, batch]
            exporters: [debug, otlp_http/collector]
          metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [debug, otlp_http/collector]
          logs:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [debug, otlp_http/collector]      
