apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: mongodb
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
      namespace: default
    spec:
      containers:
      - env:
          - name: MONGO_INITDB_DATABASE
            value: 'shop'
        image: mongo
        name: mongodb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
      terminationGracePeriodSeconds: 0
