---
apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 24h
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 30m
  chart:
    spec:
      chart: n8n
      version: 0.1.17
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 12h

  values:
    db:
      type: postgresdb
    postgresql:
      enabled: true
        
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "n8n"
        gethomepage.dev/group: "Tooling"
      hosts:
        - host: ${n8nIngressHost}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: n8n-tls
          hosts:
            -  ${n8nIngressHost}

