---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.openwebui.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 30m
  chart:
    spec:
      chart: open-webui
      version: 5.19.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
      interval: 12h

  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
      host: ${openwebuiIngressHost}
      tls: true
      existingSecret: open-webui-tls
    ollama:
      enabled: true
      models:
        pull:
          - deepseek-r1:1.5b
        run:
          - deepseek-r1:1.5b
      persistentVolume:
        enabled: true
        size: 10Gi
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: le-prod
        hosts:
          - host: ${ollamaIngressHost}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: ollama-tls
            hosts:
            - ${ollamaIngressHost}





