---
apiVersion: v1
kind: Namespace
metadata:
  name: etcd
  labels:
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: etcd
  namespace: flux-system
spec:
  interval: 24h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---  
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etcd
  namespace: etcd
spec:
  interval: 30m
  chart:
    spec:
      chart: etcd
      version: 10.4.1
      sourceRef:
        kind: HelmRepository
        name: etcd
        namespace: flux-system
      interval: 12h
  releaseName: etcd

  values:
    logLevel: "info"
    auth:
      rbac:
        create: false
    persistence:
      enabled: true
      size: 1Gi