---
apiVersion: v1
kind: Namespace
metadata:
  name: etcd
  labels:
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudpirates
  namespace: flux-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/cloudpirates
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etcd
  namespace: etcd
spec:
  interval: 30m
  chart:
    spec:
      chart: etcd
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: cloudpirates
        namespace: flux-system
      interval: 12h
  releaseName: etcd

  values:
    config:
      logLevel: "info"
    persistence:
      enabled: false
