---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 12h
  releaseName: external-dns

  values:
    sources:
      - crd
      - service
      - ingress
    logLevel: debug
    policy: sync

    registry: "txt"
    txtPrefix: "external-dns-"
    txtOwnerId: "k8s"
    domainFilters:
      - ${externalDnsDomainFilter}
    provider:
      name: coredns
    env:
    - name: ETCD_URLS
      value: http://etcd.etcd.svc.cluster.local:2379

