---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 8.3.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  releaseName: external-dns

  values:
    crd:
      ## @param crd.create Install and use the integrated DNSEndpoint CRD
      ##
      create: true
    sources:
      - crd
      - service
      - ingress
    logLevel: debug
    policy: sync

    registry: "txt"
    txtPrefix: "external-dns-"
    txtOwnerId: "k8s"
    domainFilters:
      - ${externalDnsDomainFilter}
    provider: coredns
    coredns:
      etcdEndpoints: "http://etcd.etcd.svc.cluster.local:2379"

