apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.namespace.yaml
- cert-manager.helmrepository.yaml
- cert-manager.helmrelease.yaml
- sealed-secrets.namespace.yaml
- sealed-secrets.helmrepository.yaml
- sealed-secrets.helmrelease.yaml
- sealed-secrets-web.helmrepository.yaml
- sealed-secrets-web.helmrelease.yaml
