---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets-web
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.bakito.net
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-web
  namespace: sealed-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets-web
      version: 3.1.7
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-web
        namespace: flux-system
      interval: 12h
  releaseName: sealed-secrets-web

  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "SealedSecrets"
      hosts:
        - paths:
            - path: /
              pathType: ImplementationSpecific
          host: ${sealedSecretsIngressHost}
      tls:
        - hosts:
          - ${sealedSecretsIngressHost}
          secretName: sealed-secrets-web-tls
