---
apiVersion: v1
kind: Namespace
metadata:
  name: qdrant
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: qdrant
  namespace: flux-system
spec:
  interval: 24h
  url: https://cowboysysop.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: qdrant
spec:
  interval: 30m
  chart:
    spec:
      chart: qdrant
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: flux-system
      interval: 12h

  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Qdrant"
        gethomepage.dev/group: "Apps"
      hosts:
         - host: ${qdrantIngressHost}
           paths:
             - /
      tls:
        - secretName: qdrant-tls
          hosts:
            - ${qdrantIngressHost}

