apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-vars
  namespace: flux-system
data:
  clusterName: "gpu-cluster"
  ciliumLoadBalancerIPPoolBlockStart: "192.168.10.215"
  ciliumLoadBalancerIPPoolBlockStop: "192.168.10.219"
  corednsServiceAnnotationCiliumLBIPAddrMgmt: "192.168.10.215"
  traefikServiceAnnotationCiliumLBIPAddrMgmt: "192.168.10.216"
