---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/clusters/staging
  prune: true
  wait: true
  postBuild:
    substitute:
      flowiseIngressHost: "flowise.staging.k8s.vincentdupain.com"
      homepageIngressHost: "homepage.staging.k8s.vincentdupain.com"
      n8nIngressHost: "n8n.staging.k8s.vincentdupain.com"
      ollamaIngressHost: "ollama.staging.k8s.vincentdupain.com"
      opensearchIngressHost: "logging.staging.k8s.vincentdupain.com"
      openwebuiIngressHost: "open-webui.staging.k8s.vincentdupain.com"
      podinfoIngressHost: "podinfo.staging.k8s.vincentdupain.com"
      qdrantIngressHost: "qdrant.staging.k8s.vincentdupain.com"
