apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-vars
  namespace: flux-system
data:
  homepageHostname: "homepage.staging.vincentdupain.com"
  ollamaHostname: "ollama.staging.vincentdupain.com"
  openwebuiHostname: "open-webui.staging.vincentdupain.com"
  podinfoHostname: "podinfo.staging.vincentdupain.com"