apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-vars
  namespace: flux-system
data:
  clusterName: "staging"
  ciliumLoadBalancerIPPoolBlockStart: "192.168.10.215"
  ciliumLoadBalancerIPPoolBlockStop: "192.168.10.220"
  corednsServiceAnnotationCiliumLBIPAddrMgmt: "192.168.10.215"
  traefikServiceAnnotationCiliumLBIPAddrMgmt: "192.168.10.216"
  externalDnsDomainFilter: "staging.vincentdupain.com"
  alertmanagerIngressHost: "alertmanager.staging.vincentdupain.com"
  grafanaIngressHost: "grafana.staging.vincentdupain.com"
  prometheusIngressHost: "prometheus.staging.vincentdupain.com"
  sealedSecretsIngressHost: "sealedsecrets.staging.vincentdupain.com"
