apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-vars
  namespace: flux-system
data:
  clusterName: "staging"
  ciliumLoadBalancerIPPoolBlockStart: "192.168.50.208"
  ciliumLoadBalancerIPPoolBlockStop: "192.168.50.213"
  corednsServiceAnnotationCiliumLBIPAddrMgmt: "192.168.50.208"
  traefikServiceAnnotationCiliumLBIPAddrMgmt: "192.168.50.209"
  externalDnsDomainFilter: "staging.vincentdupain.com"
  alertmanagerHostname: "alertmanager.staging.vincentdupain.com"
  grafanaHostname: "grafana.staging.vincentdupain.com"
  prometheusHostname: "prometheus.staging.vincentdupain.com"
  sealedSecretsHostname: "sealedsecrets.staging.vincentdupain.com"
  gatewayDomain: "staging.vincentdupain.com"
  gatewayLoadBalancerIP: "192.168.50.210"
