apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager-webhook-ovh.helmrepository.yaml
- cert-manager-webhook-ovh.helmrelease.yaml
- ovh-credentials.sealedsecret.yaml

