---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 33.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h
  releaseName: traefik

  values:
    deployment:
      kind: Deployment
      replicas: 2
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        io.cilium/lb-ipam-ips: ${traefikServiceAnnotationCiliumLBIPAddrMgmt}

