---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    vector.dev/exclude: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    vector.dev/exclude: "true"

