---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 24h
  url: https://jameswynn.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
      interval: 12h

  values:
    config:
      useExistingConfigMap: homepage-config

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: le-prod
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Homepage"
          gethomepage.dev/group: "Apps"
        hosts:
          - host: ${homepageIngressHost}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - ${homepageIngressHost}
