apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-vars
  namespace: flux-system
data:
  openwebuiIngressHost: "open-webui.ai.vincentdupain.com"
  ollamaIngressHost: "ollama.ai.vincentdupain.com"
  podinfoIngressHost: "podinfo.ai.vincentdupain.com"
