apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-vars
  namespace: flux-system
data:
  openwebuiHostname: "open-webui.ai.vincentdupain.com"
  ollamaHostname: "ollama.ai.vincentdupain.com"
  n8nHostname: "n8n.ai.vincentdupain.com"
  podinfoHostname: "podinfo.ai.vincentdupain.com"
  homepageHostname: "homepage.ai.vincentdupain.com"
