apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- demo-pve1-cluster.yaml
#- demo-pve3-cluster.gitignore.yaml
- gitrepo.yaml
#- proxmox-secrets.secret.yaml
#- vms/demo-rocky.yaml
#- vms/rocky.configmap.yaml
