{
 "title": "OpenSearch Prometheus Kubernetes",
 "description": "OpenSearch cluster monitoring with OpenSearch Prometheus Exporter and Node Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(opensearch_cluster_status{}, cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(opensearch_cluster_status{cluster=\"$cluster\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_status{cluster=~\"$cluster\"}) / count(opensearch_cluster_nodes_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_nodes_number{cluster=~\"$cluster\"}) / count(opensearch_cluster_nodes_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Data Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_datanodes_number{cluster=~\"$cluster\"}) / count(opensearch_cluster_datanodes_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_pending_tasks_number{cluster=~\"$cluster\"}) / count(opensearch_cluster_pending_tasks_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"active\"}) / count(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"active_primary\"}) / count(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"active_primary\"})"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"initializing\"}) / count(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"initializing\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"relocating\"}) / count(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"relocating\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"unassigned\"}) / count(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"unassigned\"})"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "irate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"opensearch\",pod=~\"$pod\"}[5m]) * 100",
     "legendFormat": "{{ pod }}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "failure_tstamp"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])*8",
     "legendFormat": "recv {{device}} {{pod}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])*8",
     "legendFormat": "trans {{device}} {{pod}}"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Documents Indexed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(opensearch_indices_merges_total_docs_count{cluster=~\"$cluster\"})",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(opensearch_indices_store_size_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Index Size"
    }
   ]
  },
  {
   "title": "Documents Indexed Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(opensearch_indices_indexing_index_count{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(opensearch_indices_search_fetch_count{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(opensearch_threadpool_tasks_number{cluster=~\"$cluster\", name!=\"management\", type=\"queue\"}) by (name)",
     "legendFormat": "Name: {{ name }}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Thread Pools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(opensearch_threadpool_threads_number{cluster=~\"$cluster\", name!=\"management\", type=\"active\"}) by (name)",
     "legendFormat": "Name: {{ name }}"
    }
   ]
  },
  {
   "title": "Total Disk Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_fs_total_available_bytes{cluster=~\"$cluster.*\"} / opensearch_fs_total_total_bytes{cluster=~\"$cluster.*\"} * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Avg. CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(irate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$pod.*\"}[5m])) * 100",
     "legendFormat": "{{ mode }}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "failure_tstamp"
    }
   ]
  },
  {
   "title": "Thread pool rejections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(opensearch_threadpool_threads_count{cluster=~\"$cluster\", name!=\"management\", type=\"rejected\"}[5m])",
     "legendFormat": "{{ node }} {{ name }}"
    }
   ]
  },
  {
   "title": "Avg Heap in 15min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(opensearch_jvm_mem_heap_used_bytes{cluster=~\"$cluster\"}[15m]) / opensearch_jvm_mem_heap_max_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "RX/TX Rate 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(opensearch_transport_rx_packets_count{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(opensearch_transport_tx_packets_count{cluster=~\"$cluster\"}[5m])) * -1",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(opensearch_jvm_gc_collection_time_seconds{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{ node }} {{ gc }}"
    }
   ]
  }
 ]
}