{
 "title": "Proxmox power usage using Scaphandre",
 "description": "Show Proxmox cluster power usage measured with Scaphandre.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pve_node",
    "query": {
     "query": "label_values(scaph_host_power_microwatts,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts{instance=~\"$pve_node\"} / 1000000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Proxmox Energy Usage\n\nPower consumption metrics for Promox clusters using Scaphandre. https://github.com/hubblo-org/scaphandre"
   }
  },
  {
   "title": "Hosts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts{instance=~\"$pve_node\"} / 1000000",
     "legendFormat": "{{ job}}"
    }
   ]
  },
  {
   "title": "Scaphandre",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=\"/usr/bin/scaphandre\", instance=~\"$pve_node\"} / 1000000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processes using > 0.01W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{instance=~\"$pve_node\"} / 1000000 > 0.01",
     "legendFormat": "{{exe}}"
    }
   ]
  }
 ]
}