apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- logging.namespace.yaml
- opensearch-dashboards.helmrelease.yaml
- opensearch.helmrelease.yaml
- opensearch.helmrepo.yaml
- opensearch.sealedsecret.yaml
- opensearch.servicemonitor.yaml
- post-config.configmap.yaml
- post-config.job.yaml
- prometheus.sealedsecret.yaml
- vector.agent.yaml
- vector.sealedsecret.yaml
#- plugins
