apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch
  namespace: logging
spec:
  releaseName: opensearch
  interval: 1m
  timeout: 10m
  chart:
    spec:
      chart: opensearch
      version: 2.32.0
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
 
  values:
    envFrom:
      - secretRef:
          name: opensearch-secrets

    sysctlInit:
      enabled: true

    persistence:
      enabled: true
      size: 5Gi
