---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vector-secret
  namespace: logging
spec:
  encryptedData:
    VECTOR_PASSWORD: AgDDBI7iYuD+Zj7Oi+Z1vhD/60gHNKe/4y9Ux34fxdW/nT6rH7j9jhEwv8+pSOF52gfvHmV/ULxHIQAqyraviV0y/luqp6gXjKbKwyZnUbxL30xH3Gal7I3vRPz6J8XierBXjWtiDes2RtSg+E/+LfKMfH+vn9jy1zZZ9Z0/q41NQemJdu9fGdGEmyfV2j0iIHP2eir2ycsgtB/99/WCLlNBzAU2kdnWFJVWQlXEk/VViVF6GAayJN8PpcRJoS7XLbJ8wkuoLwfcIm5BqQJbAPrlwomdcdqcw84scpq/GFk4hfGjhWm621xJzvGTCD6wqMvyPSgk3SIgQUcjnAYHqpk0bc83JQS2UueYyTBOqOtnI40FJ/WRSIVbhM9ck3F80/piwZOhKne/hIu8atuZSmFjmsu13wwRLxjGyVz9CWWI7s7uT1N/005VXb22qoqY5JnwkpoKMIOoelC8sdagJHWYD5hOacijhU3UDJXiJlTOFFbc+Lf3rs4DRU5Z/xQH3V+jPSdT8AydgYBI4KgPAc6zUL2Sixwx9yuLLwIfZSIohZcQdQCun5qOzn2RzWkIpz0lsFerBUd9cCvux4ECpgoWiHrrX37SGgKCu2A7DgkMY1aNPYHiMPyWEn94Vc3afIftCMor3uU2L0wkWq4aVpFAHDOL38j1Yj5XUWh0BBIo60GU2rvHTksfHHOyByh1fFFvowArr14dMLE/j0bge16BlmOWAk8LyQ==
    VECTOR_USERNAME: AgAwRTSSmn1Y79RSnogLm1Py30aOz7ZNNgjRdAhh2YzyuB2XZCpwAdF+LMbpA+cpwXlWeDEyiVKw7b6yGG57ULdLo94xA0oec6eZZCFXyDfkU7oVnYEIcawPqN9ySp26ES/6fp/fnmolMHJlZ01diVpOghZRZ6mPz6+YFIHv4k5AkpEy5i6lu/OSsD8+VpW7qp4JrosnIw0IThIgxYxDJnojl9k7YG8RxrEmSj7qc4y8w5w5RvpnTwRypGN13KG0JJeZ5v4/nxf8nascNqTPIafYTbjQvY1V3x5PvY/8+B4ly4yhRIjafZbsar/LCm63x77oiNxsvZhPUx9LXZPWHF0hFQXA6/fsklX4GROCKco21NkAgRD1hl+jrU81xxr8pHISSFRag3kL7xBb2MS44xOu/ttDi1JPBL+jNOPsBg6GRruE9sjOjTUHJIk5Qc+/zWQk0wOzS+7gJLCb+JqaZFmx02dDqV9v+TQOlpe3Hj16ZEMxcL/Hpfd2YgQ9q2nPPEpZHh4N9/fH9akGsfc2Lg+NOLNuQpSTbGstrmTclZTxDb28bBgwBZbc/yXaXVrjlJt44R668slbrzmSOZamngNMvQdJi2jd+Y51msNaHnMQiowcl2/SYxWx1m7dWicgNP+7GPEK6yELuuKfGDkBcSiys19C2jjeb8hQXtNhs6l+Th+nMtgrwxkgSUyWr451S3emtesqxg==
  template:
    metadata:
      creationTimestamp: null
      name: vector-secret
      namespace: logging
    type: Opaque
