---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vector-secret
  namespace: logging
spec:
  encryptedData:
    VECTOR_PASSWORD: AgCJ3JLaAS4uhDrtgj/EhR7XDYtawWXcuyot3cZe2ezcY0NbkOu8c83hbsD831DFa7AcMyfXb77pChRavOVvXVqX9J+3MKLsS/cMi0LQLc1z6fPAU6D3Hv9WorPyqe7wfVKei90QtDFHzYO3+YWH4RsTFWRsr87aisuvSM9Y7flDxGFTACS2CZQHUXFzDi1SUHEs/TNAfRasoiKnCnMq+9N1tmkYWNq0I6+YPoqdrgi0BTUUildyUH9exDXScQW0asQL7HAJBaqM8psvcBXcu4BM8PyiyYzTb7d5A9xH9I81BTxet4FHrg1kP67ngjwCW4YlBBOhGBuP7MrMZU3k5gegRe9+QSugT0IdvBvmMbxJrD2GS5u8a8nSZYV272FRcaz1AJhCg6bDx3qEmpLpWH7GYbFxuL+7fN7nZZDBoDCSXiG2uh/oRwmJV44MhnojZ94r7NSe5rHutyPFSd8iXpojr5kNk/im9Hbk9nggMO5GtJdabPMxkz4rd8p2cpCKE4IqiubjhF31l3AYSl0BHCWvBwsPv+HzoBgmJfBa6OU+AJdKHvguKytyysty3pRjW8ZtdtmnCst7AIDFa9Z3NwiZa7tiv6MAB/Hx6ywfN5TSOQKTgEwAMBLq9X7HjseNw5S+VN1uU/E9bt0B/c+MZIPzNkuvl2TpIsXPqdVAkBmvEjhKXaWtOVhpMIo2McV5kL5k+vx1ieMq3cS9gcE6ULQ96NR3gNg5FQ==
    VECTOR_USERNAME: AgACiLbP+hqzjLaqmxgrtpEXn8kgKHimxw35j8d5Ci8kQYpUG7/qVLVcJSRw6V+y/EuH5DbEvcjR5hKBggulJvx6HWTy8SBnBkoDBQYGN6EbqOjvlZyqbedkJnDtKFP2htdZEVeDBr5itPZPsc7PLXZFDpMOBOROF4PAaXGWkLTfM7/BpJNdx0jhs8ugkCL7/KIaih0Qg7fXG3Q4/Q7a5XR4FoGJ6i4n2tjrnmbYSXRPYsaNgDGFvUUd9ZI4YykBGLTMaNDa+qB8WAiE0DG+lKuvLsjFWS+peEmOl9HBBXOyB/XAxSg7I7jWRV4iSFyUmKYB4bU5KpCe+3gpTmdHd4VcPN+Od7cejJS6zUT2DOVYhiYyd+3lbrln2FMhYplYwQq4p8LRMk/Udh0POUZrUjmJcShNT4tk3dxCjq0ty+8P5jrjp1fdHovShVfUUi4rzfjEUld5m/m1AyrPZYGD6l6arZ6SHOKxiWza+u94IiBY8JrQywWmU+6THi1wl0SR1V+hvZ0Y5Un3Vj5w3rHncELaOsVo/QsNOf/zLa7o57hcZiFM4YFZez3bwDZNC4+GpjpEKvEiGgFlmvIvY9HfhMMRQytMN/lBP4aPAMW1KWi0dGQWdynuuX73BZzpqjROeDmNZ6GyPU8QoAwPwHIiJ9mV5IxBSHSg7e6bDM73htQpeS3Uk0yzuBn4IBlqLkbhJHzrh6wGuw==
  template:
    metadata:
      creationTimestamp: null
      name: vector-secret
      namespace: logging
    type: Opaque
