---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vector-secret
  namespace: logging
spec:
  encryptedData:
    VECTOR_PASSWORD: AgCmcDvXXIDxTqV2bpVzaepw7jRNPzHmVKqTVoM8aADOjMNjGPv0SuBrHXuYkUoen2L7kUxHX2mM/ZZDTxV+yLAmJ1S3X6FPlby9StK7qpwlGRyglsGwV1boCxs5tza7OamIfyr9EfSi7SzsuTb1+jzmFzP8ZthJI5CyU1xLqT2GNLBS1XzImHioURxmP14u0XTUKTn2S5j0rZRyiz2eBIg2pcevSRJorUMqefm1AXM1YIMjH7Kwg+IvK0pb2fk1KcFZZhTff9DX1cbnvwdl+7cRHf+eRNSAIe7gVTfFGZSHolu1lXv25IH46OzqefVl4xbmUvwQuvIF+ZavFDd1V9htSmI8B6vb7QqiFaAFuGculVCBe5mL991eUeVIDvEmFD7mcIdpWmfWLMh8wPy/Q17kqWQeEnycBmsIzo5KnHXbPP8j1d0VOIRMEBAEBM56Nv5evTeF0y61pSRiXdej6q8S8OjmaAaKCrQCVtq9hWY8mWgGNnX5L6olg/4h+ZO+pXATEgNodL+LUCq7N09G2scADUnAFFNyYh7LWoF7s1aug83Ji0TC+ve2nHw/5pJTytsnWVJlTsLILAoWXLAq5oQFHzX46/AdkdbKn4DocVwW5ooQYcqZvBbDCuIpPhFoXVHnjGMdRlTnI8VB7slN7GzGELCuyFHpDFgNKsjGrYrvUtbadXsuLWo3VqrQUXhQpYPJ2ioz2ciYV81DwXnq/GdVH5FIPotEUA==
    VECTOR_USERNAME: AgAwXA4fOC6PZXki8cHC9xtILrrYYBODyvLvjujUCAOULYCsRhVdlAAM9t5GBKbkmwE2WeBeavSx1YrqAlFGnrD1Yx28mZ4/LdBHthmlUxMTopXIMoW9cPCnv4fts1THYrsexw+mIWl+et7+aFdH6M5z4LJFGsJeZrcT0bW93Apusbxdf0sUgdJnIBS+1ZPA0Yq/n+vGoxX0hBIyTLn1/Ntcm1WXphx1tkzF+oT0wQCdZrBBHsjwpuZs9OW1lWnMjJOTZGlyb03qwChAZUNhQCwGEuklAz+bf2du/lNbAZaFb1D23PhKU8Rb4k3DvxW2Yu1OD6Bx79by/DlxD3Q8AhwI3/QtaaRpuEBMc27sC5fqdnoYqHu9iSRmab9tzNL1ZoQYcfSkihgPhcaHHSSWcpJ3ULGiQhpCh/a2NN8fNpn/IqA1NCywA3jkWwty64EbP82/NWiKyN+FYlYnauOQm7A1VcBQrSVzdPc9xzT0rqGEdH8T0Fsh16iVclSIWcXND3Ihx/6WtEGvf3wSP9JOlo9XkW5FuIM+d2YFFaVghfIfwfdNaklTqGshzb2dmskMV7dHpLkioHmLsJC14LXK4Xw3SBZ3k+1qgyeBbu9pZr+XbcK4zQp1NkYkr30Ikx9cKhgMoNO8HsEsSpZ1moHBl6bAr1x3OVbHYDIxNhlltf4uIt7AR8HhbEBSORk/QZsXWkSHAUgmiw==
  template:
    metadata:
      creationTimestamp: null
      name: vector-secret
      namespace: logging
    type: Opaque
