---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnamicharts
  namespace: flux-system
spec:
  interval: 24h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql 
      version: 16.4.14
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: flux-system
      interval: 12h
