apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 30m
  chart:
    spec:
      chart: podinfo
      version: 6.7.1
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 12h
  releaseName: podinfo

  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Podinfo"          
        gethomepage.dev/group: "Apps"          
      hosts:
        - host: ${podinfoIngressHost}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: podinfo-tls
          hosts:
            - ${podinfoIngressHost}