apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- monitoring.namespace.yaml
- prometheus-community.helmrepository.yaml
- prometheus.helmrelease.yaml
- metrics-server.namespace.yaml
- metrics-server.helmrepository.yaml
- metrics-server.helmrelease.yaml
